### ISSUE TITLE
How much time do 46 epochs cost for pascal voc 2012

### ISSUE THREAD

**Issue by ykp1992** [YudeWang/deeplabv3plus-pytorch#10]
I am sorry to bother again. I have run the code for training on pascal voc 2012 with the backbone of resnet-101. But one epoch takes me 30 minutes. I train the network with 4 GPUs and the batch_size is 16. I think it is a little slow compared with tensorflow. So, I want to ask how much time do 46 epochs cost normally.

**Comment by YudeWang** [comment]
@ykp1992 It will take about 12 hours with 4 Titan xp GPU and the batch_size is 16.

**Comment by ykp1992** [comment]
> @ykp1992 It will take about 12 hours with 4 Titan xp GPU and the batch_size is 16.

Thank you for replying! I use 4 Titan xp GPU and it will take me 18 hours. Is the random scale process that cost the extra time? Again, thank you for replying.

**Comment by YudeWang** [comment]
@ykp1992 Have you ever change the code? I use the config.py setting and cost about 12 hours ( I am not very clear, at most 14 hours). I guess if someone use the cpu at the same time with you, the training time will increase significantly.

**Comment by ykp1992** [comment]
> @ykp1992 Have you ever change the code? I use the config.py setting and cost about 12 hours ( I am not very clear, at most 14 hours). I guess if someone use the cpu at the same time with you, the training time will increase significantly.

Emmm, no, I didn't change the code. Well, maybe some other factors cause it. However, may I ask another question about the result you offer? You got the 79.155 with no multi-scale and flip setting. Is that mean the DATA_RANDOMSCALE is 1 and the DATA_RANDOMFLIP is 0. 
![image](https://user-images.githubusercontent.com/20219194/53775123-3a419c00-3f2c-11e9-85da-a7af046a3b7d.png)
I want to control my experiment settings and really look forward to your replying. Thank you.

**Comment by YudeWang** [comment]
@ykp1992 multi-scale & flip test is controled by TEST_MULTISCALE and TEST_FLIP. Most of DATA_RANDOMxxx is the setting of random data augmentation during training period. You can check the code in /lib/dataset/VOCDataset.py

**Comment by ykp1992** [comment]
> @ykp1992 multi-scale & flip test is controled by TEST_MULTISCALE and TEST_FLIP. Most of DATA_RANDOMxxx is the setting of random data augmentation during training period. You can check the code in /lib/dataset/VOCDataset.py
Oh, I see. Thank you for your replying. I am still a freshman and you do offer a lot help.

**Comment by ykp1992** [comment]
Hello, I have finished training deeplab v3+ and got 77.30(30000steps) with test_scale = [1.0] and test_flip = False.  I want to ask is it a normal result. I really need to reproduce the result in the paper and your help is necessary.  If I train the network for a few more times, can I get the result in the paper? Thank you.

**Comment by ykp1992** [comment]
Thank you！I got 78.61 in another training result!
