### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by zmghub** [YudeWang/deeplabv3plus-pytorch#13]
作者你好，感谢您的工作，最近我在复现deeplabv3plus的一些效果，有几个点略有疑惑，
1.当我直接使用deeplab-xception的结构在pascal数据集上训练时，由于样本数量有限，总是出现过拟合的情况，即便是加载了您代码中提供的xception预训练模型也如此，因此我想了解一下您是如何复现成功的。
2.您提供的deeplab-xception-46的预训练模型是在哪些数据集上训练出来的呢？

**Comment by YudeWang** [comment]
@zmghub 1. 使用VOC aug数据集（见Dataset第二条）；2. 提供的deeplabv3+xception是VOC2012aug训完的，可以直接用
