### ISSUE TITLE
Performence on cityscape

### ISSUE THREAD

**Issue by neineimeow** [YudeWang/deeplabv3plus-pytorch#14]
你好，我按照您的做法，设置epoch=160，lr=0.007,但是的到的mIOU大约在17%左右，而且我使用的是您提供的Xception_imagnet的pretrain的模型，请问您最近有重新训练吗？能不能repo您的训练结果和loss的曲线噶给我？谢谢！

**Comment by YudeWang** [comment]
不好意思最近我没有训练，以及测试协议不能直接使用CityscapeDataset.py里的do_python_eval()，而需使用cityscape官方测试脚本。

**Comment by neineimeow** [comment]
感谢那你的回复，请问您对与cityscape的config文件可以分享一下吗？因为感觉cityscape和VOC在设置上会有一些不同，期待您的分享！

**Comment by neineimeow** [comment]
您好，请问官方的测试脚本如何使用呢？能将您相关的代码分享给我吗？谢谢您！

**Comment by YudeWang** [comment]
@muomi 训练参数与VOC的config基本一致（除了迭代次数和图片尺寸），你可以自己根据计算资源进行设置。官方测试脚本请前往cityscape官网获取，建议先把目标数据集研究透了再做实验。

**Comment by neineimeow** [comment]
road          : 0.932      nan
sidewalk      : 0.696      nan
building      : 0.849      nan
wall          : 0.423      nan
fence         : 0.352      nan
pole          : 0.349      nan
traffic light : 0.262      nan
traffic sign  : 0.414      nan
vegetation    : 0.867      nan
terrain       : 0.501      nan
sky           : 0.899      nan
person        : 0.557    0.331
rider         : 0.266    0.093
car           : 0.868    0.752
truck         : 0.451    0.129
bus           : 0.533    0.222
train         : 0.287    0.122
motorcycle    : 0.163    0.064
bicycle       : 0.516    0.270
--------------------------------
Score Average : 0.536    0.248
你好，这是我lr=0.007,batchsize=4,epoch =160,cropsize=(512,1024)的训练结果，和deeplabv3+公布的结果相差很多，deeplabv3+的官方是batchsize=1，num_step = 90K，cropsize=769

**Comment by YudeWang** [comment]
@muomi 感谢提供的反馈，那你可以先按照官方参数设置训练一下。我最近是真的没有空做cityscape的实验.......如果取得好的结果也欢迎一起维护项目啊～

**Comment by neineimeow** [comment]
好~

**Comment by txfs1926** [comment]
@muomi 
您好，不知道您有没有尝试设置bn学习率为0，因为如果batch_size过小的话，bn的表现会非常不稳定，我见过其他的分割模型复现也经常在Optimizer处忽略对bn学习率的设置。期待您尝试冻结bn层的结果。
@YudeWang 
我想请问一下您在PASCAL VOC实验中是否设置了bn层的学习率？谢谢
