### ISSUE TITLE
About atrous/Multi-Grid

### ISSUE THREAD

**Issue by Spritea** [YudeWang/deeplabv3plus-pytorch#19]
Hi:
    
Nice work! But I found a place below which might be wrong. https://github.com/YudeWang/deeplabv3plus-pytorch/blob/81af60530fc1bc341bee0ea58c16a83f2da77f11/lib/net/resnet_atrous.py#L123

In the DeepLab v3 paper, author introduces the Multi-grid, or atrous variable here. 

![paper](https://user-images.githubusercontent.com/22995173/56211033-a0702180-6089-11e9-931b-1bacc9dea908.png)

The author takes an example that when OS=16 with multi-grid=(1,2,4), the rates should be (2,4,8). However, code here  would give a rates of (1,2,4), which is wrong. So `atrous` part of this line should be change to

`atrous=[item*32//os for item in atrous]`

Is that right?

**Comment by YudeWang** [comment]
@Spritea 
It is true that the dilation rates do not keep the same with original paper setting. While you should change here from [2,2,2] to [2,4,8]:
https://github.com/YudeWang/deeplabv3plus-pytorch/blob/81af60530fc1bc341bee0ea58c16a83f2da77f11/lib/net/resnet_atrous.py#L195
The code `atrous=[item*16//os for item in atrous]` is used to set 2*[2,4,8] for output_stride=8

**Comment by Spritea** [comment]
Got it! Thanks.
