### ISSUE TITLE
  VOC augmented segmentation dataset from DrSleep

### ISSUE THREAD

**Issue by lcaikk1314** [YudeWang/deeplabv3plus-pytorch#2]
感谢你的分享，有个问题：说明里要下载 VOC augmented segmentation dataset从你给定的网址DrSleep，下载下来的图是单通道灰度图，而VOC官网下载的图是三通道彩图，这样做的目的是什么？

**Comment by YudeWang** [comment]
voc有一个颜色到类别的固定映射关系，读取三通道彩色图需要转成对应类别标注；而aug dataset里给的直接就是逐像素的类别标注。
