### ISSUE TITLE
VOC augmented segmentation dataset 

### ISSUE THREAD

**Issue by Wangyf46** [YudeWang/deeplabv3plus-pytorch#20]
你好，请问你知道VOC augmented segmentation dataset 这个VOC增广数据集在哪里下载吗？？
谢谢

**Comment by YudeWang** [comment]
The download link has been given in README, please read again carefully.

Or click here.
https://www.dropbox.com/s/oeu149j8qtbs1x0/SegmentationClassAug.zip?dl=0

**Comment by Wangyf46** [comment]
你好，因为readme里面打不开，所有我才提问的，您现在给的链接也打不开，方便分享一下压缩包吗？谢谢

**Comment by YudeWang** [comment]
@Wangyf46 
Here is a VPN.
https://github.com/getlantern/lantern
