### ISSUE TITLE
xception training time

### ISSUE THREAD

**Issue by Colorfu1** [YudeWang/deeplabv3plus-pytorch#21]
我用xception的模型跑自己的数据，大概20w张图，现在跑了两天，一轮训练的结果都没有跑完，请问这个进度是不是有异常。因为相同的数据使用deeplabv3跑，两天可以训练40个轮次。请问是不是哪里出了问题。

**Comment by YudeWang** [comment]
@Colorfu1 
VOC aug每个epoch 10582张图，batchsize=16，46epoch大概跑14h（4张Titan xp），每个epoch 0.3h
你一个epoch 20w张图，相同配置一个epoch大概6h。

确实有点慢，会不会和输入图片尺寸有关系，我这里默认是512x512
