### ISSUE TITLE
Two question about transform on dataset

### ISSUE THREAD

**Issue by Balabala-Hong** [YudeWang/deeplabv3plus-pytorch#26]
你好，我没有找到你对数据集的归一化处理，是不是这一操作没有什么效果？另一个问题是定义数据集的类的时候发现图像的读取代码是：
```
image = cv2.imread(img_file)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
#image = np.array(io.imread(img_file), dtype=np.uint8)
```
这个注释掉的用skimage读取图像的代码是不是可以用来替换掉前两行的opecv读取代码的？

**Comment by YudeWang** [comment]
@Lelouch-Ice 你好，归一化在
https://github.com/YudeWang/deeplabv3plus-pytorch/blob/f9d3ed5d30adb12decbc0adb902f0e9d5f1a258f/lib/datasets/transform.py#L227
直接归一化到[0,1]，没有减均值除方差

注释掉的那行你可以试试......我已经忘记了......

**Comment by Balabala-Hong** [comment]
抱歉，我还有个小问题，在train.py里定义损失函数忽略的灰度值是255，
`criterion = nn.CrossEntropyLoss(ignore_index=255)`
但我发现在transform.py里的图像增强比如旋转、剪切、resize默认对label图片边界填充值是0，二者并不对应，这里是不是要改一下？
```
        if 'segmentation' in sample.keys():
            segmentation = sample['segmentation']
            seg = cv2.copyMakeBorder(
                segmentation,
                top,
                bottom,
                left,
                right,
                cv2.BORDER_CONSTANT,
                value=[0])
```

**Comment by YudeWang** [comment]
@Lelouch-Ice 这个我还真没发现，感觉修改成padding 255会更合适
