### ISSUE TITLE
the difference between voc and vocfinetuning?

### ISSUE THREAD

**Issue by NJU-yasuo** [YudeWang/deeplabv3plus-pytorch#28]

**Comment by NJU-yasuo** [comment]
我尝试修改了vocfinetuning的学习率，但是表现和voc完全不同，我看不出这两个程序中的任何区别，请问可以给我一点指导吗

**Comment by YudeWang** [comment]
@njuww vocfinetuning是只在train set上做微调而不是在train_aug，因为train set的标注更加准确

**Comment by NJU-yasuo** [comment]
是这样的，我尝试用vocfinetune里的train从头训练，并修了了config中的AUG=True，但是在学习率0.007的情况下LOSS为nan，我不太理解为什么会出现这种情况

**Comment by YudeWang** [comment]
@njuww finetuning是对trainaug的训练结果微调

**Comment by NJU-yasuo** [comment]
我理解你的意思，只是我对比了deepv3+voc和deepv3+vocfinetuning中的train，似乎除了args之外都是一致的，所以我不明白为什么在相同学习率下他们的结果完全不同，而且似乎deeplab3+voc的训练更慢一些？

**Comment by YudeWang** [comment]
@njuww deeplabv3+vocfinetuning固定了bn
https://github.com/YudeWang/deeplabv3plus-pytorch/blob/f9d3ed5d30adb12decbc0adb902f0e9d5f1a258f/experiment/deeplabv3%2Bvocfinetuning/train.py#L66

**Comment by NJU-yasuo** [comment]
谢谢啦

**Comment by NJU-yasuo** [comment]
finetune之后在验证集上的miou达到了89%，是aug中包含了部分val的数据集吗

**Comment by YudeWang** [comment]
@njuww 这要看你生成的train.txt里包含的数据了= =

**Comment by NJU-yasuo** [comment]
是按照你给的那个aug的label生成的


发自我的iPhone

------------------ Original ------------------

**Comment by YudeWang** [comment]
@njuww 
trainaug set包含10582，train 1464，val 1449，test 1456，后面三个都是官方给的
第一个的list你最好再check一下

**Comment by NJU-yasuo** [comment]
是的，问题已经解决了

**Comment by NJU-yasuo** [comment]
原始数据精度79%，但是finetune之后似乎精度下降了？
