### ISSUE TITLE
cannot use xception backbone with pretrained checkpoint

### ISSUE THREAD

**Issue by jt78kim** [YudeWang/deeplabv3plus-pytorch#35]
Hello.

Thanks for the great code.
I have a question about using xception as a backbone.
I modified config.py to run the code with xception backbone & pretrained checkpoint
-----------------------------------------------------------------
   self.MODEL_BACKBONE = 'xception'
   ...
   self.TEST_CKPT = os.path.join(self.ROOT_DIR,'lib/deeplabv3plus_xception_VOC2012_epoch46_all.pth')

-----------------------------------------------------------------
But I got some errors when I run the code with this configuration.

==============================================================
Traceback (most recent call last):
  File "test.py", line 94, in <module>
    test_net()
  File "test.py", line 27, in test_net
    net = generate_net(cfg)
  File "/home/jtkim/project/lgd_2nd/ref_code/deeplabv3plus-pytorch-master/lib/net/generateNet.py", line 15, in generate_net
    return deeplabv3plus(cfg)
  File "/home/jtkim/project/lgd_2nd/ref_code/deeplabv3plus-pytorch-master/lib/net/deeplabv3plus.py", line 51, in __init__
    self.backbone = build_backbone(cfg.MODEL_BACKBONE, os=cfg.MODEL_OUTPUT_STRIDE)
  File "/home/jtkim/project/lgd_2nd/ref_code/deeplabv3plus-pytorch-master/lib/net/backbone.py", line 25, in build_backbone
    net = xception.xception(pretrained=pretrained, os=os)
  File "/home/jtkim/project/lgd_2nd/ref_code/deeplabv3plus-pytorch-master/lib/net/xception.py", line 239, in xception
    model.load_state_dict(model_dict) 
  File "/home/jtkim/.conda/envs/DeepLab/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Xception:
	Unexpected key(s) in state_dict: "module.aspp.branch1.0.weight", ...
===========================================================

It seems like network models described in the pretrained checkpoint and the code are not matched. Please give me some advice about this problem.
It's perfectly run when I use resnet 101.
 

Thanks,

**Comment by YudeWang** [comment]
Hi @jt78kim ,

Thanks for your question. It is caused by nn.DataParallel. I train the network on GPUs using nn.DataParallel and save the model parameter directly. Original network state_dict for Xception likes "aspp.branch1.0.weight", but it becomes "module.aspp.branch1.0.weight" with nn.DataParallel.

If you want to reload the checkpoint on CPU, please remove prefix "module." of each key.

**Comment by jt78kim** [comment]
Hi YudeWang,

Thank you for your help. :-)
But, can I ask a few more questions?

1. I also ran the code with pretrained checkpoint "deeplabv3plus_res101_atrous_VOC2012_epoch46_all.pth" and there was no issue. I think that this pretrained checkpoint also has prefix "module." doesn't it?
2. I am running the code on GPU (4*Titan XP) do I still need to remove the prefix "module." of each key?

I'm sorry for bothering you with these questions. 
Actually I'm a SoC (semiconductor) designer so I'm not familiar with SW programming like pytorch :-(
But I'm trying to implement DeepLabv3+ on FPGA for a research purpose.
It would be great if you help me out.

Best Regards

**Comment by YudeWang** [comment]
Hi @jt78kim ,

If you contain the code to wrap net by `net = nn.DataParallel(net)` just like in test.py https://github.com/YudeWang/deeplabv3plus-pytorch/blob/09c406e84123ef3b6584cc64e2a66694c592c9d2/experiment/deeplabv3%2Bvoc/test.py#L36
then do not remove 'module.', otherwise remove it.

Maybe you should keep the same configuration for resnet and xception except `self.MODEL_BACKBONE`, `self.TEST_CKPT ` and retest with `self.TEST_GPUS=4`.

**Comment by jt78kim** [comment]
Hi @YudeWang.

Thanks for your help.
I just modified experiment/deeplabv3+voc/config.py
self.MODEL_BACKBONE and self.TEST_CKPT everything else except these two is same with the original code.
Still, I've got this error only when I use xception backbone.

**Comment by YudeWang** [comment]
Hi @jt78kim 

I am sorry that I can not guess the setting of your project. I just retest the code and it works on both resnet and xception. Maybe you should download the code again to make sure nothing has been changed?

**Comment by jt78kim** [comment]
Hi @YudeWang 

Thanks for your help.
I'll download the code again and retry the test :-)

**Comment by jt78kim** [comment]
Hi @YudeWang 

While I download the code and retry the test, I found there was one mistake that I've made.
I set 'torch.save(net.state_dict()' in lib/test_script.py same as 'TEST_CKPT' in config.py.
I changed 'torch.save(net.state_dict()' to 'data.lip6.fr/cadene/pretrainedmodels/xception-b5690688.pth'.
Now I got errors a little different from the previous one.
Could you please check the below errors and give me some advice?

===================================================
 File "test.py", line 94, in <module>
    test_net()
  File "test.py", line 27, in test_net
    net = generate_net(cfg)
  File "/home/jtkim/project/lgd_2nd/ref_code/new/deeplabv3plus-pytorch-master/lib/net/generateNet.py", line 15, in generate_net
    return deeplabv3plus(cfg)
  File "/home/jtkim/project/lgd_2nd/ref_code/new/deeplabv3plus-pytorch-master/lib/net/deeplabv3plus.py", line 51, in __init__
    self.backbone = build_backbone(cfg.MODEL_BACKBONE, os=cfg.MODEL_OUTPUT_STRIDE)
  File "/home/jtkim/project/lgd_2nd/ref_code/new/deeplabv3plus-pytorch-master/lib/net/backbone.py", line 25, in build_backbone
    net = xception.xception(pretrained=pretrained, os=os)
  File "/home/jtkim/project/lgd_2nd/ref_code/new/deeplabv3plus-pytorch-master/lib/net/xception.py", line 239, in xception
    model.load_state_dict(model_dict) 
  File "/home/jtkim/.conda/envs/DeepLab/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Xception:
	Unexpected key(s) in state_dict: "bn3.weight", "bn3.bias", "bn3.running_mean", "bn3.running_var", "bn4.weight", "bn4.bias", "bn4.running_mean", "bn4.running_var", "fc.weight", "fc.bias", "block1.rep.0.conv1.weight", "block1.rep.0.pointwise.weight", "block1.rep.1.weight", "block1.rep.1.bias", "block1.rep.1.running_mean", "block1.rep.1.running_var", "block1.rep.3.conv1.weight", "block1.rep.3.pointwise.weight", "block1.rep.4.weight", "block1.rep.4.bias", "block1.rep.4.running_mean", "block1.rep.4.running_var", "block2.rep.1.conv1.weight", "block2.rep.1.pointwise.weight", "block2.rep.2.weight", "block2.rep.2.bias", "block2.rep.2.running_mean", "block2.rep.2.running_var", "block2.rep.4.conv1.weight", "block2.rep.4.pointwise.weight", "block2.rep.5.weight", "block2.rep.5.bias", "block2.rep.5.running_mean", "block2.rep.5.running_var", "block3.rep.1.conv1.weight", "block3.rep.1.pointwise.weight", "block3.rep.2.weight", "block3.rep.2.bias", "block3.rep.2.running_mean", "block3.rep.2.running_var", "block3.rep.4.conv1.weight", "block3.rep.4.pointwise.weight", "block3.rep.5.weight", "block3.rep.5.bias", "block3.rep.5.running_mean", "block3.rep.5.running_var", "block4.rep.1.conv1.weight", "block4.rep.1.pointwise.weight", "block4.rep.2.weight", "block4.rep.2.bias", "block4.rep.2.running_mean", "block4.rep.2.running_var", "block4.rep.4.conv1.weight", "block4.rep.4.pointwise.weight", "block4.rep.5.weight", "block4.rep.5.bias", "block4.rep.5.running_mean", "block4.rep.5.running_var", "block4.rep.7.conv1.weight", "block4.rep.7.pointwise.weight", "block4.rep.8.weight", "block4.rep.8.bias", "block4.rep.8.running_mean", "block4.rep.8.running_var", "block5.rep.1.conv1.weight", "block5.rep.1.pointwise.weight", "block5.rep.2.weight", "block5.rep.2.bias", "block5.rep.2.running_mean", "block5.rep.2.running_var", "block5.rep.4.conv1.weight", "block5.rep.4.pointwise.weight", "block5.rep.5.weight", "block5.rep.5.bias", "block5.rep.5.running_mean", "block5.rep.5.running_var", "block5.rep.7.conv1.weight", "block5.rep.7.pointwise.weight", "block5.rep.8.weight", "block5.rep.8.bias", "block5.rep.8.running_mean", "block5.rep.8.running_var", "block6.rep.1.conv1.weight", "block6.rep.1.pointwise.weight", "block6.rep.2.weight", "block6.rep.2.bias", "block6.rep.2.running_mean", "block6.rep.2.running_var", "block6.rep.4.conv1.weight", "block6.rep.4.pointwise.weight", "block6.rep.5.weight", "block6.rep.5.bias", "block6.rep.5.running_mean", "block6.rep.5.running_var", "block6.rep.7.conv1.weight", "block6.rep.7.pointwise.weight", "block6.rep.8.weight", "block6.rep.8.bias", "block6.rep.8.running_mean", "block6.rep.8.running_var", "block7.rep.1.conv1.weight", "block7.rep.1.pointwise.weight", "block7.rep.2.weight", "block7.rep.2.bias", "block7.rep.2.running_mean", "block7.rep.2.running_var", "block7.rep.4.conv1.weight", "block7.rep.4.pointwise.weight", "block7.rep.5.weight", "block7.rep.5.bias", "block7.rep.5.running_mean", "block7.rep.5.running_var", "block7.rep.7.conv1.weight", "block7.rep.7.pointwise.weight", "block7.rep.8.weight", "block7.rep.8.bias", "block7.rep.8.running_mean", "block7.rep.8.running_var", "block8.rep.1.conv1.weight", "block8.rep.1.pointwise.weight", "block8.rep.2.weight", "block8.rep.2.bias", "block8.rep.2.running_mean", "block8.rep.2.running_var", "block8.rep.4.conv1.weight", "block8.rep.4.pointwise.weight", "block8.rep.5.weight", "block8.rep.5.bias", "block8.rep.5.running_mean", "block8.rep.5.running_var", "block8.rep.7.conv1.weight", "block8.rep.7.pointwise.weight", "block8.rep.8.weight", "block8.rep.8.bias", "block8.rep.8.running_mean", "block8.rep.8.running_var", "block9.rep.1.conv1.weight", "block9.rep.1.pointwise.weight", "block9.rep.2.weight", "block9.rep.2.bias", "block9.rep.2.running_mean", "block9.rep.2.running_var", "block9.rep.4.conv1.weight", "block9.rep.4.pointwise.weight", "block9.rep.5.weight", "block9.rep.5.bias", "block9.rep.5.running_mean", "block9.rep.5.running_var", "block9.rep.7.conv1.weight", "block9.rep.7.pointwise.weight", "block9.rep.8.weight", "block9.rep.8.bias", "block9.rep.8.running_mean", "block9.rep.8.running_var", "block10.rep.1.conv1.weight", "block10.rep.1.pointwise.weight", "block10.rep.2.weight", "block10.rep.2.bias", "block10.rep.2.running_mean", "block10.rep.2.running_var", "block10.rep.4.conv1.weight", "block10.rep.4.pointwise.weight", "block10.rep.5.weight", "block10.rep.5.bias", "block10.rep.5.running_mean", "block10.rep.5.running_var", "block10.rep.7.conv1.weight", "block10.rep.7.pointwise.weight", "block10.rep.8.weight", "block10.rep.8.bias", "block10.rep.8.running_mean", "block10.rep.8.running_var", "block11.rep.1.conv1.weight", "block11.rep.1.pointwise.weight", "block11.rep.2.weight", "block11.rep.2.bias", "block11.rep.2.running_mean", "block11.rep.2.running_var", "block11.rep.4.conv1.weight", "block11.rep.4.pointwise.weight", "block11.rep.5.weight", "block11.rep.5.bias", "block11.rep.5.running_mean", "block11.rep.5.running_var", "block11.rep.7.conv1.weight", "block11.rep.7.pointwise.weight", "block11.rep.8.weight", "block11.rep.8.bias", "block11.rep.8.running_mean", "block11.rep.8.running_var", "block12.skip.weight", "block12.skipbn.weight", "block12.skipbn.bias", "block12.skipbn.running_mean", "block12.skipbn.running_var", "block12.rep.1.conv1.weight", "block12.rep.1.pointwise.weight", "block12.rep.2.weight", "block12.rep.2.bias", "block12.rep.2.running_mean", "block12.rep.2.running_var", "block12.rep.4.conv1.weight", "block12.rep.4.pointwise.weight", "block12.rep.5.weight", "block12.rep.5.bias", "block12.rep.5.running_mean", "block12.rep.5.running_var", "conv3.conv1.weight", "conv4.conv1.weight". 
	size mismatch for conv3.pointwise.weight: copying a param with shape torch.Size([1536, 1024]) from checkpoint, the shape in current model is torch.Size([1536, 1024, 1, 1]).
	size mismatch for conv4.pointwise.weight: copying a param with shape torch.Size([2048, 1536]) from checkpoint, the shape in current model is torch.Size([1536, 1536, 1, 1]).
===================================================

**Comment by YudeWang** [comment]
Hi @jt78kim ,

I find you use `torch.save(net.state_dict())`, then the saved model file should reload by the net without nn.DataParallel wrapping.

And I guess you load the file `/cadene/pretrainedmodels/xception-b5690688.pth`, it does not match with my xception.py. Please use the checkpoint given in my README.md

**Comment by jt78kim** [comment]
Hi @YudeWang 

Thanks for your help.
It's a little bit difficult for me to run the code. :-(

Honestly, I don't know how I can reload the net without nn.DataParallel wrapping.
Here's what I've done after downloading the code.
Could you please take a look?

1. modify experiment/deeplabv3+voc/config.py
    self.MODEL_BACKBONE = 'xception'
    self.TEST_CKPT = '.../deeplabv3plus_xception_VOC2012_epoch46_all.pth'

2. lib/net/xception.py
    model_urls : same as TEST_CKPT

3. lib/test_script.py - I don't know whether this file is used or not in your code
    torch.save(net.state_dict())

4. put VOCdevkit input data/

I just want to run the code and check the output for now.
Should I do something else for testing?

**Comment by YudeWang** [comment]
Hi @jt78kim ,
It seems that my code writing is not good enough hhhhhhh.
1. The step is correct.
2. The reason of bugs. Here you should replace the url path to `your_path/xception_pytorch_imagnet` given in README instead of `your_path/deeplabv3plus_xception_VOC2012_epoch46_all.pth`.
3. `lib/test_script.py` is useless.
4. I have not found bugs caused by dataset yet.

**Comment by jt78kim** [comment]
Hi @YudeWang 

Now I can run the test with xception backbone.
I should have read your code carefully. 
Thank you very much for your help again :-)
