### ISSUE TITLE
hello，请问img为什么没有减mean除以std？

### ISSUE THREAD

**Issue by opee007** [YudeWang/deeplabv3plus-pytorch#37]
rt..

**Comment by YudeWang** [comment]
@opee007 
我直接归一化到[0,1]了，其实严格来说应该按照与训练的归一化方式进行归一化，你可以根据自己实际使用情况进行修改

**Comment by opee007** [comment]
> @opee007
> 我直接归一化到[0,1]了，其实严格来说应该按照与训练的归一化方式进行归一化，你可以根据自己实际使用情况进行修改

我使用减mean除以std的方式 ，pascal val的iou只能到0.68，而直接归一化到[0,1]，iou可以到75，随然都没到达到论文中的效果，请问您有什么见解吗，另外，我发现你使用的bn层momentum仅设置为0.0003,而不是默认的0.1，我设置问0.0003之后收敛的很慢(还在跑着..)，请问你差不多多少个epoch可以收敛。最后 ，我仔细看了你的vocdataloader，我发现你的做法有其他deeplabV3+的开源代码不太一样，你没有使用空白像素填充小于512的图片，而是直接resize，请问这样会对最后结果有影响吗，我怎么做才能达到论文中的结果。。谢谢！！再次谢谢！

**Comment by YudeWang** [comment]
@opee007 
归一化影响不应该这么大吧，我也试过减mean除std但并没有很大影响。

bn_mom=0.0003是deeplabv3论文里的4.1 training protocol 'The batch
normalization parameters are trained with decay = 0.9997', 总共训练30k itr，用batchsize=16大约46epoch

crop和resize两种方法我后来都试过，用resize在单尺度测试能达到paper性能但多尺度不行，用crop则反过来了（其实我个人建议用crop，这里都是我早期代码，有考虑不周的因素）

**Comment by opee007** [comment]
> @opee007
> 归一化影响不应该这么大吧，我也试过减mean除std但并没有很大影响。
> 
> bn_mom=0.0003是deeplabv3论文里的4.1 training protocol 'The batch
> normalization parameters are trained with decay = 0.9997', 总共训练30k itr，用batchsize=16大约46epoch
> 
> crop和resize两种方法我后来都试过，用resize在单尺度测试能达到paper性能但多尺度不行，用crop则反过来了（其实我个人建议用crop，这里都是我早期代码，有考虑不周的因素）

bn_mom和decay有关系吗..我使用了crop ，bn_mom使用默认的0.1刚刚单尺度跑到了0.80，我如果用0.0001bn_mom的话训练起来一直不收敛啊..

**Comment by YudeWang** [comment]
@opee007 
其实我试的时候bn_mom=0.0003和0.1没有太大的差别
