### ISSUE TITLE
Bad Performance

### ISSUE THREAD

**Issue by chenyzh28** [YudeWang/deeplabv3plus-pytorch#4]
I have downloaded the deeplabv3plus_xception_VOC2012_epoch60_all.pth，but the val result is only 0.032. Do you know what happened?

**Comment by YudeWang** [comment]
I retest the provide model deeplabv3plus_xception_VOC2012_epoch60_all.pth and achieve exactly 81.937% mIoU. Maybe you should check the configuration in config.py again about MODEL_BACKBONE, etc.

**Comment by YudeWang** [comment]
The repository has been update recently and the pretrained model on COCO is removed due to the change of network structure. I will update once achieve.

I will close the issue for no more discussion. You can also contact me by email yude.wang@outlook.com is necessary.

**Comment by YourGc** [comment]
I get same issue ! And found when i try net.eval() ,the performance will be bad, but I get good performance with code "with torch.no_gard()" 
  So? Is some issue in BN?
