### ISSUE TITLE
关于ASPP的结构，有疑问

### ISSUE THREAD

**Issue by zhangbanxian123** [YudeWang/deeplabv3plus-pytorch#41]
根据您提供的ASPP源码，根据deeplabv3+的模型结构，branch5应该是池化操作，但在您的源码中，branch5是卷积操作，如下所示：
		self.branch5_conv = nn.Conv2d(dim_in, dim_out, 1, 1, 0,bias=True)
		self.branch5_bn = SynchronizedBatchNorm2d(dim_out, momentum=bn_mom)
		self.branch5_relu = nn.ReLU(inplace=True)
是否应该为：
		self.branch5_pool = nn.AdaptiveAvgPool2d(（1,1）) #此处由卷积操作改为池化操作
		self.branch5_bn = SynchronizedBatchNorm2d(dim_out, momentum=bn_mom)
		self.branch5_relu = nn.ReLU(inplace=True)
期待回答~

**Comment by YudeWang** [comment]
https://github.com/YudeWang/deeplabv3plus-pytorch/blob/09c406e84123ef3b6584cc64e2a66694c592c9d2/lib/net/ASPP.py#L54-L59
