### ISSUE TITLE
voc test.py mIOU value is error

### ISSUE THREAD

**Issue by cwwng** [YudeWang/deeplabv3plus-pytorch#49]
I reappear the project, the training result feels ok. But the mIOU value tested was only 20.733%.
Training configuration information:
1. Use deeplabv3+voc folder under train.py test.py
2. Use VOCdevkit data sets
3, self.data_aug = False
4. Self.TRAIN_BATCHES = 10
5, self.train_epochs = 300
6. Backbone res101_atrous has no pretraining model parameter for the base model

Test configuration information:
Self. DATA_AUG = False
Self. TEST_MULTISCALE = [1.0]
Self. TEST_BATCHES = 18

Screenshots of training and testing:
<img width="414" alt="acc" src="https://user-images.githubusercontent.com/12265892/76858209-e8975580-6891-11ea-87e1-23ada02544c4.png">
<img width="387" alt="loss" src="https://user-images.githubusercontent.com/12265892/76858217-eaf9af80-6891-11ea-8943-a580c885c29a.png">
![test-miou](https://user-images.githubusercontent.com/12265892/76858222-ec2adc80-6891-11ea-848e-e850dcd238f4.jpeg)

When you want to ask test what's wrong with the mIOU value being so low.

**Comment by 2679622694** [comment]
I have the same problem

**Comment by YudeWang** [comment]
@cwwng @2679622694 
It seems the model has overfitted on training set. Pure VOC training set is not enough (1400+ images). Please use VOC augmentation dataset (10582 images) with `self.data_aug = True`

**Comment by 2679622694** [comment]
I used VOC augmentation dataset，but the value of loss does not converge。After about 30,000 steps, it's always above 1

**Comment by 2679622694** [comment]
How long have you been training at voc augmentation dataset?

**Comment by YudeWang** [comment]
@2679622694 
Then you guys are in different cases. Please provide more details of yours.
The default setting is given in `config.py` which is 46 epoch (about 30K iteration)

**Comment by 2679622694** [comment]
self.EXP_NAME = 'deeplabv3+voc'
		self.DATA_NAME = 'VOC2012'
		self.DATA_AUG = False
		self.DATA_WORKERS = 0
		self.DATA_RESCALE = 512
		self.DATA_RANDOMCROP = 512
		self.DATA_RANDOMROTATION = 0
		self.DATA_RANDOMSCALE = 2
		self.DATA_RANDOM_H = 10
		self.DATA_RANDOM_S = 10
		self.DATA_RANDOM_V = 10
		self.DATA_RANDOMFLIP = 0.5
		
		self.MODEL_NAME = 'deeplabv3plus'
		self.MODEL_BACKBONE = 'res101_atrous'
		self.MODEL_OUTPUT_STRIDE = 16
		self.MODEL_ASPP_OUTDIM = 256
		self.MODEL_SHORTCUT_DIM = 48
		self.MODEL_SHORTCUT_KERNEL = 1
		self.MODEL_NUM_CLASSES = 21
		self.MODEL_SAVE_DIR = os.path.join(self.ROOT_DIR,'model',self.EXP_NAME)

		self.TRAIN_LR = 0.007
		self.TRAIN_LR_GAMMA = 0.1
		self.TRAIN_MOMENTUM = 0.9
		self.TRAIN_WEIGHT_DECAY = 0.00004
		self.TRAIN_BN_MOM = 0.0003
		self.TRAIN_POWER = 0.9
		self.TRAIN_GPUS = 4
		self.TRAIN_BATCHES = 2
		self.TRAIN_SHUFFLE = True
		self.TRAIN_MINEPOCH = 0	
		self.TRAIN_EPOCHS = 46
		self.TRAIN_LOSS_LAMBDA = 0
		self.TRAIN_TBLOG = True
		self.TRAIN_CKPT = None#os.path.join(self.ROOT_DIR,'model/deeplabv3+voc/deeplabv3plus_xception_VOC2012_itr0.pth')

		self.LOG_DIR = os.path.join(self.ROOT_DIR,'log',self.EXP_NAME)

		self.TEST_MULTISCALE = [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
		self.TEST_FLIP = True
		self.TEST_CKPT = os.path.join(self.ROOT_DIR,'model/deeplabv3+voc/deeplabv3plus_res101_atrous_VOC2012_epoch46_all.pth')
		self.TEST_GPUS = 4
		self.TEST_BATCHES = 4

		self.__check()
		self.__add_path(os.path.join(self.ROOT_DIR, 'lib'))


I'm running out of memory so I made num_work batchsize small

**Comment by cwwng** [comment]
在VOC2012数据集上， self.DATA_AUG = False 要设置成True。

**Comment by cwwng** [comment]
> ```
>           self.EXP_NAME = 'deeplabv3+voc'
> 	self.DATA_NAME = 'VOC2012'
> 	self.DATA_AUG = False
> 	self.DATA_WORKERS = 0
> 	self.DATA_RESCALE = 512
> 	self.DATA_RANDOMCROP = 512
> 	self.DATA_RANDOMROTATION = 0
> 	self.DATA_RANDOMSCALE = 2
> 	self.DATA_RANDOM_H = 10
> 	self.DATA_RANDOM_S = 10
> 	self.DATA_RANDOM_V = 10
> 	self.DATA_RANDOMFLIP = 0.5
> 	
> 	self.MODEL_NAME = 'deeplabv3plus'
> 	self.MODEL_BACKBONE = 'res101_atrous'
> 	self.MODEL_OUTPUT_STRIDE = 16
> 	self.MODEL_ASPP_OUTDIM = 256
> 	self.MODEL_SHORTCUT_DIM = 48
> 	self.MODEL_SHORTCUT_KERNEL = 1
> 	self.MODEL_NUM_CLASSES = 21
> 	self.MODEL_SAVE_DIR = os.path.join(self.ROOT_DIR,'model',self.EXP_NAME)
> 
> 	self.TRAIN_LR = 0.007
> 	self.TRAIN_LR_GAMMA = 0.1
> 	self.TRAIN_MOMENTUM = 0.9
> 	self.TRAIN_WEIGHT_DECAY = 0.00004
> 	self.TRAIN_BN_MOM = 0.0003
> 	self.TRAIN_POWER = 0.9
> 	self.TRAIN_GPUS = 4
> 	self.TRAIN_BATCHES = 2
> 	self.TRAIN_SHUFFLE = True
> 	self.TRAIN_MINEPOCH = 0	
> 	self.TRAIN_EPOCHS = 46
> 	self.TRAIN_LOSS_LAMBDA = 0
> 	self.TRAIN_TBLOG = True
> 	self.TRAIN_CKPT = None#os.path.join(self.ROOT_DIR,'model/deeplabv3+voc/deeplabv3plus_xception_VOC2012_itr0.pth')
> 
> 	self.LOG_DIR = os.path.join(self.ROOT_DIR,'log',self.EXP_NAME)
> 
> 	self.TEST_MULTISCALE = [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
> 	self.TEST_FLIP = True
> 	self.TEST_CKPT = os.path.join(self.ROOT_DIR,'model/deeplabv3+voc/deeplabv3plus_res101_atrous_VOC2012_epoch46_all.pth')
> 	self.TEST_GPUS = 4
> 	self.TEST_BATCHES = 4
> 
> 	self.__check()
> 	self.__add_path(os.path.join(self.ROOT_DIR, 'lib'))
> ```
> 
> 
> I'm running out of memory so I made num_work batchsize small

在VOC2012数据集上， self.DATA_AUG = False 要设置成True。

**Comment by cwwng** [comment]
I set ‘self.data_aug’ to True to succeed.

**Comment by 2679622694** [comment]
Sorry, I pasted it wrong.I set self.data_aug'=True when I was training
Could you please check my file and have any other questions?

          self.EXP_NAME = 'deeplabv3+voc'
	self.DATA_NAME = 'VOC2012'
	self.DATA_AUG = True
	self.DATA_WORKERS = 0
	self.DATA_RESCALE = 512
	self.DATA_RANDOMCROP = 512
	self.DATA_RANDOMROTATION = 0
	self.DATA_RANDOMSCALE = 2
	self.DATA_RANDOM_H = 10
	self.DATA_RANDOM_S = 10
	self.DATA_RANDOM_V = 10
	self.DATA_RANDOMFLIP = 0.5
	
	self.MODEL_NAME = 'deeplabv3plus'
	self.MODEL_BACKBONE = 'res101_atrous'
	self.MODEL_OUTPUT_STRIDE = 16
	self.MODEL_ASPP_OUTDIM = 256
	self.MODEL_SHORTCUT_DIM = 48
	self.MODEL_SHORTCUT_KERNEL = 1
	self.MODEL_NUM_CLASSES = 21
	self.MODEL_SAVE_DIR = os.path.join(self.ROOT_DIR,'model',self.EXP_NAME)

	self.TRAIN_LR = 0.007
	self.TRAIN_LR_GAMMA = 0.1
	self.TRAIN_MOMENTUM = 0.9
	self.TRAIN_WEIGHT_DECAY = 0.00004
	self.TRAIN_BN_MOM = 0.0003
	self.TRAIN_POWER = 0.9
	self.TRAIN_GPUS = 4
	self.TRAIN_BATCHES = 2
	self.TRAIN_SHUFFLE = True
	self.TRAIN_MINEPOCH = 0	
	self.TRAIN_EPOCHS = 46
	self.TRAIN_LOSS_LAMBDA = 0
	self.TRAIN_TBLOG = True
	self.TRAIN_CKPT = None#os.path.join(self.ROOT_DIR,'model/deeplabv3+voc/deeplabv3plus_xception_VOC2012_itr0.pth')

	self.LOG_DIR = os.path.join(self.ROOT_DIR,'log',self.EXP_NAME)

	self.TEST_MULTISCALE = [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
	self.TEST_FLIP = True
	self.TEST_CKPT = os.path.join(self.ROOT_DIR,'model/deeplabv3+voc/deeplabv3plus_res101_atrous_VOC2012_epoch46_all.pth')
	self.TEST_GPUS = 4
	self.TEST_BATCHES = 4

	self.__check()
	self.__add_path(os.path.join(self.ROOT_DIR, 'lib'))

**Comment by cwwng** [comment]
什么问题，把错误贴一下



            
            
                
                    
                            
                                
                            
                            
                                364464702
                            
                    
                        
                            
                                    邮箱：364464702@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


            On 05/14/2020 18:57, 2679622694 wrote: 
Sorry, I pasted it wrong.I set self.data_aug'=True when I was training
Could you please check my file and have any other questions?
      self.EXP_NAME = 'deeplabv3+voc'
self.DATA_NAME = 'VOC2012'
self.DATA_AUG = True
self.DATA_WORKERS = 0
self.DATA_RESCALE = 512
self.DATA_RANDOMCROP = 512
self.DATA_RANDOMROTATION = 0
self.DATA_RANDOMSCALE = 2
self.DATA_RANDOM_H = 10
self.DATA_RANDOM_S = 10
self.DATA_RANDOM_V = 10
self.DATA_RANDOMFLIP = 0.5

self.MODEL_NAME = 'deeplabv3plus'
self.MODEL_BACKBONE = 'res101_atrous'
self.MODEL_OUTPUT_STRIDE = 16
self.MODEL_ASPP_OUTDIM = 256
self.MODEL_SHORTCUT_DIM = 48
self.MODEL_SHORTCUT_KERNEL = 1
self.MODEL_NUM_CLASSES = 21
self.MODEL_SAVE_DIR = os.path.join(self.ROOT_DIR,'model',self.EXP_NAME)

self.TRAIN_LR = 0.007
self.TRAIN_LR_GAMMA = 0.1
self.TRAIN_MOMENTUM = 0.9
self.TRAIN_WEIGHT_DECAY = 0.00004
self.TRAIN_BN_MOM = 0.0003
self.TRAIN_POWER = 0.9
self.TRAIN_GPUS = 4
self.TRAIN_BATCHES = 2
self.TRAIN_SHUFFLE = True
self.TRAIN_MINEPOCH = 0		
self.TRAIN_EPOCHS = 46
self.TRAIN_LOSS_LAMBDA = 0
self.TRAIN_TBLOG = True
self.TRAIN_CKPT = None#os.path.join(self.ROOT_DIR,'model/deeplabv3+voc/deeplabv3plus_xception_VOC2012_itr0.pth')

self.LOG_DIR = os.path.join(self.ROOT_DIR,'log',self.EXP_NAME)

self.TEST_MULTISCALE = [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
self.TEST_FLIP = True
self.TEST_CKPT = os.path.join(self.ROOT_DIR,'model/deeplabv3+voc/deeplabv3plus_res101_atrous_VOC2012_epoch46_all.pth')
self.TEST_GPUS = 4
self.TEST_BATCHES = 4

self.__check()
self.__add_path(os.path.join(self.ROOT_DIR, 'lib'))


—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/YudeWang/deeplabv3plus-pytorch/issues/49#issuecomment-628557327",
"url": "https://github.com/YudeWang/deeplabv3plus-pytorch/issues/49#issuecomment-628557327",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by YudeWang** [comment]
@2679622694 
The training batchsize is too small, the default is 16 with 4 GPUs

**Comment by 2679622694** [comment]
好的 谢谢了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hibercraft"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月14日(星期四) 晚上8:03
收件人:&nbsp;"YudeWang/deeplabv3plus-pytorch"<deeplabv3plus-pytorch@noreply.github.com&gt;;
抄送： &nbsp;“ 2679622694” <2679622694@qq.com&gt;;“提及” <mention@noreply.github.com&gt;;
主题:&nbsp;Re: [YudeWang/deeplabv3plus-pytorch] voc test.py mIOU value is error (#49)





 
@ 2679622694
  训练批次大小太小，默认值为16，带有4个GPU
  
- 
您收到此邮件是因为有人提到您。
直接回复此电子邮件，在GitHub上查看，或取消订阅。
