### ISSUE TITLE
Training and Testing with ADE20K Dataset

### ISSUE THREAD

**Issue by binging512** [YudeWang/deeplabv3plus-pytorch#51]
Hi! I trained DeepLabv3+ with ADE20K dataset, but the test mIoU can just reach 36.3%, even can’t match with UperNet (its mIoU can reach 42%). I just wonder why it happened. I will appreciate it if someone can tell me how to solve this problem. Thanks a lot.

**Comment by YudeWang** [comment]
@binging512 
I think the ADE20K is more complex than PASCAL VOC & CityScapes with lots of details and context information. There are many dilated conv in DeepLabv3+, which may be good for large object, but the architecture for the combination of deep & shallow layer features is too simple. These designs lead to failure on tiny objects and complex scene. Moreover, ADE20K has more categories than  VOC & CityScapes, maybe the 256-dim ASPP is not enough.

**Comment by binging512** [comment]
> @binging512 
> 
> I think the ADE20K is more complex than PASCAL VOC & CityScapes with lots of details and context information. There are many dilated conv in DeepLabv3+, which may be good for large object, but the architecture for the combination of deep & shallow layer features is too simple. These designs lead to failure on tiny objects and complex scene. Moreover, ADE20K has more categories than  VOC & CityScapes, maybe the 256-dim ASPP is not enough.

Ok, I got it. Thanks for your reply. :-)
