### ISSUE TITLE
模型在cityscapes数据集上的性能问题

### ISSUE THREAD

**Issue by pingjun18-li** [YudeWang/deeplabv3plus-pytorch#53]
感谢您贡献这么优秀的工程，由于个人兴趣以及研究需求，对cityscapes数据集上的训练存在一定的疑问：您的数据读入CityscapesDataset.py是否需要做一定修改，以及网络结构和训练参数，在issues里看到您说可以训到75%，但是我自己只能到40+%，能否共享一下该分支。期待您的回复

**Comment by YudeWang** [comment]
@Alchemist-18 
您好，CityscapesDataset.py我没有继续维护，应该需要您按照需求自己修改一下。当时自己做过cityscape的实验但是代码并没有整理所以就没有开源。
