### ISSUE TITLE
Pretrained Xception

### ISSUE THREAD

**Issue by YuyanRuan** [YudeWang/deeplabv3plus-pytorch#57]
Hi there! Thanks for the great work!!
But I ran into trouble when Xception pretrained weights. I uncomment some codes in the model, like the `bn` stuff, and also change some 1536 to 2048, but the problem is still not solved. 
`
RuntimeError: Error(s) in loading state_dict for Xception:
	Unexpected key(s) in state_dict: "bn3.weight", "bn3.bias", "bn3.running_mean", "bn3.running_var", "bn4.weight", "bn4.bias", "bn4.running_mean", "bn4.running_var", "fc.weight", "fc.bias", "block1.rep.0.conv1.weight", "block1.rep.0.pointwise.weight", "block1.rep.1.weight", "block1.rep.1.bias", "block1.rep.1.running_mean", "block1.rep.1.running_var", "block1.rep.3.conv1.weight", "block1.rep.3.pointwise.weight", "block1.rep.4.weight", "block1.rep.4.bias", "block1.rep.4.running_mean", "block1.rep.4.running_var", "block2.rep.1.conv1.weight", "block2.rep.1.pointwise.weight", "block2.rep.2.weight", "block2.rep.2.bias", "block2.rep.2.running_mean", "block2.rep.2.running_var", "block2.rep.4.conv1.weight", "block2.rep.4.pointwise.weight", "block2.rep.5.weight", "block2.rep.5.bias", "block2.rep.5.running_mean", "block2.rep.5.running_var", "block3.rep.1.conv1.weight", "block3.rep.1.pointwise.weight", "block3.rep.2.weight", "block3.rep.2.bias", "block3.rep.2.running_mean", "block3.rep.2.running_var", "block3.rep.4.conv1.weight", "block3.rep.4.pointwise.weight", "block3.rep.5.weight", "block3.rep.5.bias", "block3.rep.5.running_mean", "block3.rep.5.running_var", "block4.rep.1.conv1.weight", "block4.rep.1.pointwise.weight", "block4.rep.2.weight", "block4.rep.2.bias", "block4.rep.2.running_mean", "block4.rep.2.running_var", "block4.rep.4.conv1.weight", "block4.rep.4.pointwise.weight", "block4.rep.5.weight", "block4.rep.5.bias", "block4.rep.5.running_mean", "block4.rep.5.running_var", "block4.rep.7.conv1.weight", "block4.rep.7.pointwise.weight", "block4.rep.8.weight", "block4.rep.8.bias", "block4.rep.8.running_mean", "block4.rep.8.running_var", "block5.rep.1.conv1.weight", "block5.rep.1.pointwise.weight", "block5.rep.2.weight", "block5.rep.2.bias", "block5.rep.2.running_mean", "block5.rep.2.running_var", "block5.rep.4.conv1.weight", "block5.rep.4.pointwise.weight", "block5.rep.5.weight", "block5.rep.5.bias", "block5.rep.5.running_mean", "block5.rep.5.running_var", "block5.rep.7.conv1.weight", "block5.rep.7.pointwise.weight", "block5.rep.8.weight", "block5.rep.8.bias", "block5.rep.8.running_mean", "block5.rep.8.running_var", "block6.rep.1.conv1.weight", "block6.rep.1.pointwise.weight", "block6.rep.2.weight", "block6.rep.2.bias", "block6.rep.2.running_mean", "block6.rep.2.running_var", "block6.rep.4.conv1.weight", "block6.rep.4.pointwise.weight", "block6.rep.5.weight", "block6.rep.5.bias", "block6.rep.5.running_mean", "block6.rep.5.running_var", "block6.rep.7.conv1.weight", "block6.rep.7.pointwise.weight", "block6.rep.8.weight", "block6.rep.8.bias", "block6.rep.8.running_mean", "block6.rep.8.running_var", "block7.rep.1.conv1.weight", "block7.rep.1.pointwise.weight", "block7.rep.2.weight", "block7.rep.2.bias", "block7.rep.2.running_mean", "block7.rep.2.running_var", "block7.rep.4.conv1.weight", "block7.rep.4.pointwise.weight", "block7.rep.5.weight", "block7.rep.5.bias", "block7.rep.5.running_mean", "block7.rep.5.running_var", "block7.rep.7.conv1.weight", "block7.rep.7.pointwise.weight", "block7.rep.8.weight", "block7.rep.8.bias", "block7.rep.8.running_mean", "block7.rep.8.running_var", "block8.rep.1.conv1.weight", "block8.rep.1.pointwise.weight", "block8.rep.2.weight", "block8.rep.2.bias", "block8.rep.2.running_mean", "block8.rep.2.running_var", "block8.rep.4.conv1.weight", "block8.rep.4.pointwise.weight", "block8.rep.5.weight", "block8.rep.5.bias", "block8.rep.5.running_mean", "block8.rep.5.running_var", "block8.rep.7.conv1.weight", "block8.rep.7.pointwise.weight", "block8.rep.8.weight", "block8.rep.8.bias", "block8.rep.8.running_mean", "block8.rep.8.running_var", "block9.rep.1.conv1.weight", "block9.rep.1.pointwise.weight", "block9.rep.2.weight", "block9.rep.2.bias", "block9.rep.2.running_mean", "block9.rep.2.running_var", "block9.rep.4.conv1.weight", "block9.rep.4.pointwise.weight", "block9.rep.5.weight", "block9.rep.5.bias", "block9.rep.5.running_mean", "block9.rep.5.running_var", "block9.rep.7.conv1.weight", "block9.rep.7.pointwise.weight", "block9.rep.8.weight", "block9.rep.8.bias", "block9.rep.8.running_mean", "block9.rep.8.running_var", "block10.rep.1.conv1.weight", "block10.rep.1.pointwise.weight", "block10.rep.2.weight", "block10.rep.2.bias", "block10.rep.2.running_mean", "block10.rep.2.running_var", "block10.rep.4.conv1.weight", "block10.rep.4.pointwise.weight", "block10.rep.5.weight", "block10.rep.5.bias", "block10.rep.5.running_mean", "block10.rep.5.running_var", "block10.rep.7.conv1.weight", "block10.rep.7.pointwise.weight", "block10.rep.8.weight", "block10.rep.8.bias", "block10.rep.8.running_mean", "block10.rep.8.running_var", "block11.rep.1.conv1.weight", "block11.rep.1.pointwise.weight", "block11.rep.2.weight", "block11.rep.2.bias", "block11.rep.2.running_mean", "block11.rep.2.running_var", "block11.rep.4.conv1.weight", "block11.rep.4.pointwise.weight", "block11.rep.5.weight", "block11.rep.5.bias", "block11.rep.5.running_mean", "block11.rep.5.running_var", "block11.rep.7.conv1.weight", "block11.rep.7.pointwise.weight", "block11.rep.8.weight", "block11.rep.8.bias", "block11.rep.8.running_mean", "block11.rep.8.running_var", "block12.skip.weight", "block12.skipbn.weight", "block12.skipbn.bias", "block12.skipbn.running_mean", "block12.skipbn.running_var", "block12.rep.1.conv1.weight", "block12.rep.1.pointwise.weight", "block12.rep.2.weight", "block12.rep.2.bias", "block12.rep.2.running_mean", "block12.rep.2.running_var", "block12.rep.4.conv1.weight", "block12.rep.4.pointwise.weight", "block12.rep.5.weight", "block12.rep.5.bias", "block12.rep.5.running_mean", "block12.rep.5.running_var", "conv3.conv1.weight", "conv4.conv1.weight". 
	size mismatch for conv3.pointwise.weight: copying a param with shape torch.Size([1536, 1024]) from checkpoint, the shape in current model is torch.Size([1536, 1024, 1, 1]).
	size mismatch for conv4.pointwise.weight: copying a param with shape torch.Size([2048, 1536]) from checkpoint, the shape in current model is torch.Size([1536, 1536, 1, 1]).

`
Can anyone help? Thanks a lot!!

**Comment by hjhjb** [comment]
我已收到，谢谢

**Comment by YuyanRuan** [comment]
Ahh I think the correct link for xception weights is in the readme file... Sorry

**Comment by horo111** [comment]
> Ahh I think the correct link for xception weights is in the readme file... Sorry

Can you tell me that how do you solve that?Thank you so much,I meet the same question as yours

**Comment by YuyanRuan** [comment]
Hi there
Actually the author has changed the architecture of the Xception net a lot. Therefore, loading weights of the normal Xception network does not work. Luckily, the author has provided the pretrained weights for his/her own version, which is included here:
![image](https://user-images.githubusercontent.com/60810000/163659478-4f9b6cf3-97ef-49d1-83d8-65cd2747d310.png)

I remembered it will still prompt out an error saying size mismatch, but for this time you can easily change it. If you need any help regarding this, pleas attach a capture. (I forgot what I exactly have done.)

**Comment by horo111** [comment]
> Hi there Actually the author has changed the architecture of the Xception net a lot. Therefore, loading weights of the normal Xception network does not work. Luckily, the author has provided the pretrained weights for his/her own version, which is included here: ![image](https://user-images.githubusercontent.com/60810000/163659478-4f9b6cf3-97ef-49d1-83d8-65cd2747d310.png)
> 
> I remembered it will still prompt out an error saying size mismatch, but for this time you can easily change it. If you need any help regarding this, pleas attach a capture. (I forgot what I exactly have done.)

Sincerely thank you for your reply. According to your instructions my problem has been solved。Thank you so much

**Comment by YuyanRuan** [comment]
You are welcome~
