### ISSUE TITLE
xception pretrain on coco

### ISSUE THREAD

**Issue by 666zz666** [YudeWang/deeplabv3plus-pytorch#6]
之前转换的xception pretrain的model是不能用吗？

**Comment by YudeWang** [comment]
@666zz666  对的，我争取这两天把新训好的coco pretrain model放出来

**Comment by Colorfu1** [comment]
我用xception的模型跑自己的数据，大概20w张图，现在跑了两天，一轮训练的结果都没有跑完，请问这个进度是不是有异常。因为相同的数据使用deeplabv3跑，两天可以训练40个轮次。请问是不是哪里出了问题。

**Comment by Anikily** [comment]
大哥coco pretrain弄好了吗

**Comment by Anikily** [comment]
@YudeWang

**Comment by YudeWang** [comment]
@Anikily 鸽了鸽了......deadline太多了，随缘更新......
