### ISSUE TITLE
Core Dump error

### ISSUE THREAD

**Issue by neineimeow** [YudeWang/deeplabv3plus-pytorch#7]
你好，我在训练网络的时候发现直接报Core Dump ，后经过排查，发现时tensorboardX的问题，我之前没装过tensorboardX，请问您使用的是什么版本啊?安装的过程能详细告知吗？谢谢~

**Comment by YudeWang** [comment]
https://github.com/lanpa/tensorboardX

**Comment by neineimeow** [comment]
你好，请问这个在COCO数据集上训练需要多久啊？训练30个epoch

**Comment by YudeWang** [comment]
四张xp大概两天左右

**Comment by neineimeow** [comment]
谢谢~但是我只有两张卡，我Train的时候，总是显示out of momory,改小batchsize和GPU个数，还是不行，请问还有哪里需要修改吗？

**Comment by YudeWang** [comment]
out of memory报显存不够啊。。。当然只能继续改小batchsize啊。。。或者你有别的办法节约显存也可以啊。。。

**Comment by YudeWang** [comment]
out of memory报显存不够啊。。。当然只能继续改小batchsize啊。。。或者你有别的办法节约显存也可以啊。。。

**Comment by neineimeow** [comment]
嗯呢，谢谢！

**Comment by YudeWang** [comment]
out of memory报显存不够啊。。。当然只能继续改小batchsize。。。如果有别的节约显存的办法你也可以用啊。。。调参的细节发可以邮件联系我。
关于issue问题的讨论已结束，我会关闭这个issue
