### ISSUE TITLE
different TRAIN_BN_MOM for COCO and VOC

### ISSUE THREAD

**Issue by ChiWeiHsiao** [YudeWang/deeplabv3plus-pytorch#8]
Thank you for your decent work! I noticed that the TRAIN_BN_MOM is set to 0.0003 in deeplabv3+voc/config.py, but remains default value 0.1 for COCO experiment. 
How do you choose the value for BN momentum? I couldn't find any suggestion for BN momentum from the deeplabv3+ paper.

**Comment by YudeWang** [comment]
I check the official TF DeepLab source code before and find they set bn_mom as 0.0003 (batch_norm_decay=0.9997). You can check in https://github.com/tensorflow/models/blob/master/research/deeplab/core/xception.py

COCO experiment is just used for model pretrain, so I do not think bn_mom with small change is really important in this stage. You can choose whatever you like. I will be glad to see a better performance achieved with new parameter setting.

**Comment by ChiWeiHsiao** [comment]
Thank you!
