### ISSUE TITLE
net.module in train.py

### ISSUE THREAD

**Issue by ykp1992** [YudeWang/deeplabv3plus-pytorch#9]
Is it a mistype of net.module()

**Comment by ykp1992** [comment]
![image](https://user-images.githubusercontent.com/20219194/53692268-8c1ce180-3dc7-11e9-9581-ef720c77113f.png)
if I keep it unchanged, three would be a error “no attribute”

**Comment by ykp1992** [comment]
if I change it to net.module()，three would be another error “generator has no attribute "named_modules"”

**Comment by YudeWang** [comment]
@ykp1992 Thanks for your reminding. I guess you set gpu_num=1, which will cause the network does not packaged by nn.DataParallel and make mistake here. You can change "net.module" to "net" directly if so.

**Comment by ykp1992** [comment]
> here
Thank you for replying! I do set gpu_num=1.  So, I just have to change "net.module" to "net"  if I still want to use one gpu and I can also use two gpus with the code unchanged. Again, really thank you for replying and it really helps a lot.
